### ISSUE TITLE
Transaction issue and layout breaking

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#232]
**Tested on Ropsten** | iOS | Build 0.1.16

1. I've sent 0.2 ETH but after that in the transactions tables I see 0.2000000000011 [https://gyazo.com/fd9e74a86ea6f999e4be9389b1a9a1da](https://gyazo.com/fd9e74a86ea6f999e4be9389b1a9a1da)
2. Which also breakes the layout
3. After I login again, the transaction is entirely gone from my wallet.

Aha! Link: https://kycc.aha.io/features/MOBILE-97

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.

**Comment by rhdelima** [comment]
@maycon-mello Layout issue is not fixed yet
device: iPhone X
![image](https://user-images.githubusercontent.com/10294014/74924184-fa114d00-540c-11ea-8628-72e2259a4955.png)

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good now. Pass
