### ISSUE TITLE
KeyFi: Request additional information

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#359]
Mobile wallet should have support to redirect to KYC when additional information is required for the application.
![image](https://user-images.githubusercontent.com/12645078/100690618-ad787c00-3365-11eb-96a9-8f2749896964.png)

**Comment by maycon-mello** [comment]
This is ready for testing.

**Comment by maycon-mello** [comment]
This is deployed and ready for QA

**Comment by rhdelima** [comment]
@maycon-mello Please fix minor UI issues:
![image](https://user-images.githubusercontent.com/10294014/100865055-cc941c80-34d1-11eb-960e-98f30beeefdf.png)
![image](https://user-images.githubusercontent.com/10294014/100865086-d7e74800-34d1-11eb-9193-940c591486ac.png)

Also, Additional information message is only showing on KeyFi marketplace. Are we NOT showing it as well on Applications tab? @andregoncalves Can you confirm?

**Comment by andregoncalves** [comment]
We should show them on applications tab as well

**Comment by maycon-mello** [comment]
Thanks for testing, I will fix the issues.

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA.

**Comment by rhdelima** [comment]
@maycon-mello The `COMPLETE APPLICATION` button is now showing under Applications. However, the UI issues raised are still NOT fixed.

![image](https://user-images.githubusercontent.com/10294014/100865055-cc941c80-34d1-11eb-960e-98f30beeefdf.png)
![image](https://user-images.githubusercontent.com/10294014/100865086-d7e74800-34d1-11eb-9193-940c591486ac.png)
